export const ADD_TODO = "ADD_TODO";
export const TOGGLE_TODO = "TOGGLE_TODO_STATUS";

export const DELETE_TODO = "DELETE_TODO";

export const FILTER_COMPLETED_TASKS = "FILTER_COMPLETED_TASKS";
export const FILTER_ALL_TODOS = "FILTER_ALL_TODOS";
export const FILTER_PENDING_TODOS = "FILTER_PENDING_TODOS";

export const CHANGE_SELECTED_TAB = "CHANGE_SELECTED_TAB";
export const TOGGLE_ADD_FORM = "TOGGLE_ADD_FORM";
